// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/index.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                                            GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Qum Silk      Tabriz Wool & Silk      Naein ナイン      Kashan カシャーン          セール目玉商品                              セール500点全商品30％OFF 2025年6月1日～2025年6月30日迄                                                           &nbsp   ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs                                                                                                        The brilliance of the Persian carpet is universal              &nbsp   めまぐるしく移ろいゆく現代社会  &nbsp   の中長い伝統をもち世界の誰もが  &nbsp   認める普遍の価値と美しさを持つ  &nbsp   ペルシャ絨毯それは敷物の域を超え暮らしに彩りをそえて  &nbsp   くれるアートですくつろぎの時間を視覚から  &nbsp   そして足元の感触から演出してみませんか　                                                          本社ショールーム      GALLERY NAZARIAN      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                              &nbsp          ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/origin.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                  GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                              Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Qum Silk      Tabriz Wool & Silk      Kashan カシャーン      Naein ナイン          セール目玉商品                                    産地紹介            ペルシャ絨毯は、現在の国名イランで手織り制作されているパイル織りの敷物をさします。この世界で最も美しく、かつ耐久性に優れた敷物は４～５０００年の歴史をもつといわれイランの人々にとって暮らしの必需品として、代々国中で織り伝えられています。その織り方は各産地ごとに異なり、用いられる素材や色合いそしてデザインまでもが各地で特徴があります。              QUM Silk クムシルク    クムは東方が荒涼とした砂漠に接する地です。  織りあがった絹絨毯の仕上げ洗いに最適な水に恵まれ、  美しくつややかな作品を制作しております。  はじまりはペルシャ絨毯の歴史からいえばごく最近、  百数十年前からですが、この特徴ある水の恩恵で絹糸  からなる絨毯が盛んに制作され、産地クムは他に類を  見ない急速な発展を遂げました。  絹糸の絨毯は古くより王侯貴族や大商人といった富豪に  愛され、富と美の象徴としてその邸宅を美しく飾り  続けています。    Tabriz Wool&amp Silk    タブリーズはイランの北西部に位置し、首都テヘランに次ぐ国内第2の商業都市でマルコポーロの「東方見聞録」にもその賑わいが紹介されている歴史ある街です。  冬場は雪が数メートルも積もるタブリーズでは、羊毛を用いた絨毯が織られ一枚の絨毯に使われる色数が他産地に比べ、際立って多いことで有名です。  多彩な色は作品の華やかさを演出するだけでなく、絵画絨毯とよばれる独自の作品世界を発展させました。  &nbsp   （額装品）    タブリーズウール＆シルク            Naein Wool&amp Silk    ナイン ウール＆シルク        ナインはイランのほぼ中央に位置し、周囲を砂漠に囲まれた都市です。厳しい土地に生まれた小さなオアシス都市であったナインは、羊毛の布地産地として生計を立てておりましたが、市場の縮小に伴い、絨毯の制作を始めました。  ナイン絨毯の特徴はその抑制された配色にあり、乾いた砂漠を連想させるベージュを基調に、そこから広がっていく樹木の緑、水を表す青、命の輝きを赤で表現しているといわれております。用いられる色彩は限られていますが、どのようなインテリアスタイルにもに合わせやすい産地です。        KASHAN Wool&amp Silk    カシャーン ウール＆シルク    カシャンは数ある絨毯産地の中でも、最も歴史が長いといわれる高級絨毯の産地です。農作物の育たぬ厳しい土地柄のため、古くから陶器やタイルなど工芸品の生産が発達しました。また交易の要衝としての絶好の地理的条件を生かし、絨毯とともにビロードやダマスク織の産地としても西洋に名を広めました。  １８世紀アフガン支配の下、衰退していた絨毯業が復興した１９世紀末以降、かねてより養蚕が盛んで絹織物の伝統が長いカシャンでは、精巧で高品質な絹の絨毯が数多く織られました。                                                                                                Previous      Next             ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/maintenance.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷                                                          GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                              Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Qum Silk      Tabriz Wool & Silk      Kashan カシャーン      Naein ナイン          セール目玉商品                                                        クリーニングメンテナンスのご案内            クリーニング　/　しみぬき　　 Cleaning Service      熟練の職人が丁寧に手作業でクリーニングいたしますペットや飲み物、食べ物の汚れなどもご相談くださいしみの程度を拝見させていただいてからお見積りいたしますまた大きい絨毯はお引き取り、配達もいたします（弊社での長期保管、お客様宅での絨毯以外の家具等移動は行っておりません）                                                      補修　　　Repair      「掃除機のヘッドブラシに巻き込まれ、絨毯のふさ  がとれた」「ペットが噛んで、一部欠けてしまった」  絨毯に関するお困り事をご相談ください  絨毯とともに生きる本場イランの熟練職人の手で  また美しさを取り戻せます                                                  額装　　Framed decolation      絨毯を壁掛けにしてみませんか  手織りならではの温かみある素敵なアートになります                                                            GALLERY NAZARIAN      本社ショールーム      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                                   ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/qumsilk.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                        GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                  Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Tabriz ﾀﾌﾞﾘ-ｽﾞ      Kashan カシャーン      Naein ナイン          セール目玉商品                                                                                                            QUM Silk クムシルク      クムは東方が荒涼とした砂漠に接する地です。  織りあがった絹絨毯の仕上げ洗いに最適な水に恵まれ、美しくつややかな作品を制作しております。はじまりは  ペルシャ絨毯の歴史からいえばごく最近、百数十年前からですが、この特徴ある水の恩恵で絹糸からなる絨毯が  盛んに制作され、産地クムは他に類を見ない急速な発展を遂げました。絹糸の絨毯は古くより王侯貴族や大商人  といった富豪に愛され、富と美の象徴としてその邸宅を美しく飾り続けています。                            Qum&nbsp Silk　２００＊１３０㎝                Qum Silk　90＊60 ㎝                Qum Silk　90＊60 ㎝                Qum Silk　２００＊１３０㎝                            Qum&nbsp Silk　２００＊１３０㎝                Qum Silk　90＊60 ㎝                Qum Silk　90＊60 ㎝                Qum Silk　２００＊１３０㎝                                                                                    本社ショールーム      GALLERY NAZARIAN      〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                         ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/tabrizwoolsilk.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                        GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                  Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Qum Silk      Kashan カシャーン      Naein ナイン          セール目玉商品                                                                                                            TABRIZ WOOL &amp  SILK  &nbsp タブリーズウール＆シルク      タブリーズはイランの北西部に位置し、首都テヘランに次ぐ国内第2の商業都市でマルコポーロの「東方見聞録」  にもその賑わいが紹介されている歴史ある街です。冬場は雪が数メートルも積もるタブリーズでは、羊毛を  用いた絨毯が織られ一枚の絨毯に使われる色数が他産地に比べ、際立って多いことで有名です。  多彩な色は作品の華やかさを演出するだけでなく、絵画絨毯とよばれる独自の作品世界を発展させました。                                            TABRIZ Wool&nbsp &amp &nbsp Silk２００＊１5０㎝                TABRIZ Wool &amp  Silk 120＊80 ㎝                TABRIZ Wool &amp  Silk 120＊80 ㎝                TABRIZ Wool &amp  Silk２40＊170&nbsp ㎝                            TABRIZ Wool &amp  Silk２40＊170&nbsp ㎝                TABRIZ Wool&nbsp &amp &nbsp Silk２００＊１5０㎝                TABRIZ Wool &amp  Silk２40＊170&nbsp ㎝                TABRIZ Wool&nbsp &amp &nbsp Silk２００＊１5０㎝              &nbsp                                                                               本社ショールーム      GALLERY NAZARIAN      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                         ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/naein.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                        GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                  Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Tabriz ﾀﾌﾞﾘ-ｽﾞ      Kashan カシャーン      Qum クムシルク          セール目玉商品                                                                                                            Naein Wool＆Silkナインウール＆シルク      ナインはイランのほぼ中央に位置し、周囲を砂漠に囲まれた都市です。厳しい土地に生まれた小さなオアシス都市であったナインは、羊毛の布地産地として生計を立てておりましたが、市場の縮小に伴い、絨毯の制作を始めました。ナイン絨毯の特徴はその抑制された配色にあり、乾いた砂漠を連想させるベージュを基調に、そこから広がっていく樹木の緑、水を表す青、命の輝きを赤で表現しているといわれております。用いられる色彩は限られていますが、どのようなインテリアスタイルにもに合わせやすい産地です。                            Naein&nbsp Wool&amp Silk 240＊１60㎝                Naein&nbsp Wool&amp Silk２00＊１3０㎝                Naein&nbsp Wool&amp Silk２4０＊１5０㎝                Naein&nbsp Wool&amp Silk&nbsp  90＊6０㎝                            Naein&nbsp Wool&amp Silk300＊200㎝                Naein&nbsp Wool&amp Silk300＊200㎝                Naein&nbsp Wool&amp Silk300＊200㎝                Naein&nbsp Wool&amp Silk300＊200㎝                                                                                        本社ショールーム      GALLERY NAZARIAN      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                         ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/kashan.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                        GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                  Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Tabriz ﾀﾌﾞﾘ-ｽﾞ      Naein      Qum　クム          セール目玉商品                                                                                                            Kashan Wool＆Silk   カシャーン（シルク＆ウール）      カシャンは数ある絨毯産地の中でも、最も歴史が長いといわれる高級絨毯の産地です。農作物の育たぬ厳しい土地柄のため、古くから陶器やタイルなど工芸品の生産が発達しました。また交易の要衝としての絶好の地理的条件を生かし、絨毯とともにビロードやダマスク織の産地としても西洋に名を広めました。  １８世紀アフガン支配の下、衰退していた絨毯業が復興した１９世紀末以降、  かねてより養蚕が盛んで絹織物の伝統が長いカシャンでは、精巧で高品質な絹の絨毯が数多く織られました。                            Kashan&nbsp Wool 100＊75㎝                Kashan&nbsp Wool 100＊75㎝                Kashan&nbsp Wool 100＊75㎝                Kashan&nbsp Wool 100＊75㎝                            Kashan&nbsp Silk 150＊100㎝                Kashan&nbsp Silk 220＊140㎝                Kashan&nbsp Silk 220＊140㎝                Kashan&nbsp Wool 220＊140㎝                                                                                        本社ショールーム      GALLERY NAZARIAN      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                         ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   this[database_length++] = new SearchPage("http://www.nazarian-carpet.jp/sale.html", "ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都", "        ペルシャ絨毯 ,PersianCarpet,敷物,大田区南雪谷, 田園調布,東京都                                                                            GALLERY NAZARIAN      ギャラリーナザリアン      ペルシャ絨毯直輸入                                                Home ホーム      Origin 産地      Cleaning クリーニング＆修理      Gallery ギャラリー      Qum Silk      Tabriz Wool & Silk      Naein ナイン      Kashan カシャーン                                                                           セール500点全商品30％OFF　2025年6月1日～2025年6月30日迄                    &nbsp   ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs                                                        クムシルク  Size 150×100&nbsp ㎝  通常価格１００万円  目玉商品価格50％OFF  ￥５０万円                                                        クムシルク  Size 150×100&nbsp ㎝  通常価格１５０万円  目玉商品価格50％OFF  ￥７５万円                                                        Isfehan イスファハーン  Size 300×200 ㎝  通常価格３００万円  目玉商品価格50％OFF  １５０万円                                                        Gabbe ギャベ  Size 234x168 ㎝  通常価格３５万円  目玉商品価格50％OFF  １７．５万円                                                                                            本社ショールーム      GALLERY NAZARIAN      &nbsp &nbsp  &nbsp &nbsp  〒145-0066  東京都大田区南雪谷2-18-2  TEL 03  5499  3031  &nbsp  　 03  5499  1230                             ", "ペルシャ絨毯－敷物－インテリアｰ  Hand woven fine Persian Carpets and rugs");
   return this;
}
